
---

## 📄 install.sh

#!/bin/bash

# Pi Website Updater - Installation Script
# This script sets up the automatic website update system

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Pi Website Updater - Installation${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    echo -e "${YELLOW}Warning: Running as root is not recommended.${NC}"
    echo -e "${YELLOW}Continue? (y/n)${NC}"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Prompt for website path
echo -e "${GREEN}Step 1: Configure Website Path${NC}"
echo -n "Enter the path to your website (default: /var/www/geosmin): "
read -r SITE_PATH
SITE_PATH=${SITE_PATH:-/var/www/geosmin}
echo -e "Website path: ${YELLOW}$SITE_PATH${NC}"
echo ""

# Prompt for GitHub repo URL
echo -e "${GREEN}Step 2: Configure GitHub Repository${NC}"
echo -n "Enter your GitHub repository URL (e.g., https://github.com/user/repo.git): "
read -r REPO_URL

if [ -z "$REPO_URL" ]; then
    echo -e "${RED}Error: Repository URL is required.${NC}"
    exit 1
fi
echo -e "Repository URL: ${YELLOW}$REPO_URL${NC}"
echo ""

# Prompt for branch
echo -e "${GREEN}Step 3: Configure Branch${NC}"
echo -n "Enter branch name (default: main): "
read -r BRANCH
BRANCH=${BRANCH:-main}
echo -e "Branch: ${YELLOW}$BRANCH${NC}"
echo ""

# Confirm settings
echo -e "${GREEN}Step 4: Confirm Settings${NC}"
echo "Website Path: $SITE_PATH"
echo "Repository URL: $REPO_URL"
echo "Branch: $BRANCH"
echo ""
echo -n "Proceed with installation? (y/n): "
read -r confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 0
fi

echo ""
echo -e "${GREEN}Installing...${NC}"

# Create the update script with the configured variables
echo -e "Creating update script at /usr/local/bin/update-site.sh..."

sudo tee /usr/local/bin/update-site.sh > /dev/null << EOF
#!/bin/bash

# Website Update Script
# Generated by pi-website-updater

SITE_PATH="$SITE_PATH"
REPO_URL="$REPO_URL"
BRANCH="$BRANCH"
LOG_FILE="/var/log/update-site.log"

# Function to log messages
log_message() {
    echo "\$(date '+%Y-%m-%d %H:%M:%S'): \$1" >> \$LOG_FILE
}

log_message "========================================="
log_message "Checking for updates..."

# Check if site directory exists
if [ ! -d "\$SITE_PATH" ]; then
    log_message "ERROR: Site directory \$SITE_PATH does not exist."
    log_message "Attempting to clone repository..."
    
    # Clone the repository
    sudo git clone \$REPO_URL \$SITE_PATH
    
    if [ \$? -eq 0 ]; then
        log_message "Repository cloned successfully."
        sudo chown -R \$USER:\$USER \$SITE_PATH
        sudo chmod -R 755 \$SITE_PATH
        sudo systemctl reload nginx
        log_message "Nginx reloaded after initial clone."
    else
        log_message "ERROR: Failed to clone repository."
        exit 1
    fi
fi

# Navigate to the site directory
cd \$SITE_PATH || exit 1

# Fetch the latest changes
if ! git fetch origin; then
    log_message "ERROR: Git fetch failed."
    exit 1
fi

# Check if local branch is behind remote
LOCAL_COMMIT=\$(git rev-parse HEAD)
REMOTE_COMMIT=\$(git rev-parse origin/\$BRANCH)

if [ "\$LOCAL_COMMIT" != "\$REMOTE_COMMIT" ]; then
    log_message "Changes detected! Pulling latest code..."
    
    # Pull the latest changes
    if git pull origin \$BRANCH; then
        log_message "Pull successful."
        
        # Set permissions
        sudo chown -R \$USER:\$USER \$SITE_PATH
        sudo chmod -R 755 \$SITE_PATH
        
        # Reload Nginx
        sudo systemctl reload nginx
        log_message "Nginx reloaded."
    else
        log_message "ERROR: Git pull failed."
        exit 1
    fi
else
    log_message "No changes detected."
fi

log_message "Update check complete."
log_message "========================================="
EOF

# Make the script executable
sudo chmod +x /usr/local/bin/update-site.sh

# Create log file
sudo touch /var/log/update-site.log
sudo chmod 644 /var/log/update-site.log

# Add cron job (runs every 5 minutes)
echo -e "Adding cron job (runs every 5 minutes)..."

# Check if cron job already exists
if crontab -l 2>/dev/null | grep -q "/usr/local/bin/update-site.sh"; then
    echo -e "${YELLOW}Cron job already exists. Skipping.${NC}"
else
    (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/update-site.sh") | crontab -
    echo -e "${GREEN}Cron job added.${NC}"
fi

# Run initial update
echo -e "Running initial update..."
sudo /usr/local/bin/update-site.sh

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Installation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "✅ Update script installed: /usr/local/bin/update-site.sh"
echo "✅ Log file: /var/log/update-site.log"
echo "✅ Cron job added: Every 5 minutes"
echo ""
echo -e "${GREEN}To manually check for updates:${NC}"
echo "  sudo /usr/local/bin/update-site.sh"
echo ""
echo -e "${GREEN}To view logs:${NC}"
echo "  cat /var/log/update-site.log"
echo "  tail -f /var/log/update-site.log  (real-time)"
echo ""
echo -e "${GREEN}To remove:${NC}"
echo "  crontab -e  # Remove the line with update-site.sh"
echo "  sudo rm /usr/local/bin/update-site.sh"
echo ""